#+TITLE: Gentoo Linux Setup Guide
#+DATE: [2014-07-07 Mon 16:32]
#+KEYWORDS: gentoo
#+OPTIONS: H:5
#+SETUPFILE: ../org-templates/level-1.org

* User Administration

** Adding a User for Daily Use

The following table lists a number of important groups you might wish to use:
#+ATTR_HTML: :frame border
| Group | Description                                                                |
|-------+----------------------------------------------------------------------------|
| /     | <>                                                                         |
|-------+----------------------------------------------------------------------------|
| audio | be able to access the audio devices                                        |
|-------+----------------------------------------------------------------------------|
| usb   | be able to access USB devices                                              |
|-------+----------------------------------------------------------------------------|
| video | be able to access video capturing hardware and doing hardware acceleration |
|-------+----------------------------------------------------------------------------|
| users | group for normal users                                                     |
|-------+----------------------------------------------------------------------------|
| wheel | be able to use su                                                          |

#+BEGIN_EXAMPLE
  # Login as root first
  Login: root↲
  Password: (Your root password)↲

  # -m, --create-home; -G, --groups; -s, --shell
  useradd -m -G audio,usb,video,users,wheel -s /bin/bash (Your user name)↲

  passwd (Your user name)↲
  Password: (Enter the password)↲
  Re-enter password: (Re-enter the password to verify)↲
#+END_EXAMPLE

* Using Portage

** Specify Package Versions

According to [[http://wiki.gentoo.org/wiki/Version_specifier][Version Specifier]], we have:
1. Basic
   + category/package :: Matches any version of a package.
2. By Version
   + ~category/package-1.23 :: Matches version and any revision.
   + =category/package-1.23* :: Matches a version by the version range. Note that there's no "." before the "*".
   + =category/package-1.23 :: Matches a version exactly.
   + >=category/package-1.23 :: Matches the specified version or any higher version.
   + >category/package-1.23 :: Matches a version strictly later than specified.
   + <category/package-1.23 :: Matches a version strictly older than specified.
   + <=category/package-1.23 :: Matches the specified version or any older version.
3. By Slot
   + category/package:2 :: Matches package in the specified package SLOT. Note that there is no prefix.
4. By Overlay
   + category/package::overlay :: Matches a package from a specific overlay. This can be combined with other specifiers. The official portage tree is ::gentoo.

** Local Portage Configure Files

*** package.use/*

As for now, [2014-07-10 Thu 16:35], libav-10.2 & mpv-0.4.0 have been hard masked. Unmask them as following:
#+BEGIN_EXAMPLE
  cd /etc/portage/package.unmask↲

  cat libav↲

  >=media-video/libav-10

  cat mpv

  >=media-video/mpv-0.4
#+END_EXAMPLE

*** package.license

google-chrome requires explicit license acknowledgement:
#+BEGIN_EXAMPLE
  cat /etc/portage/package.license↲

  >=www-client/google-chrome-35.0.1916.114_p1 google-chrome
#+END_EXAMPLE

*** package.use

Custom USE flags for individual package. For USE flags defined in
Gentoo's profile ~desktop~[fn:1] but *missing* in ~no-multilib~, don't
forget to add them manually.
#+BEGIN_EXAMPLE
  cat /etc/portage/package.use↲

  >=dev-libs/libxml2-2.9.1-r4 python
  >=x11-wm/fvwm-2.6.5 png truetype
  >=x11-terms/rxvt-unicode-9.20 256-color xft alt-font-width -vanilla perl
  >=sys-libs/zlib-1.2.8-r1 minizip
  >=media-libs/harfbuzz-0.9.23 icu
  >=dev-libs/libxml2-2.9.1-r4 icu
  >=app-arch/p7zip-9.20.1 rar
  >=app-editors/emacs-24.3 gif jpeg png svg tiff xft
  #video
  >=x11-libs/libva-1.3.1 opengl
  >=media-libs/mesa-10.2 dri3 -vaapi -llvm -gallium

  >=dev-vcs/git-2.0 -perl -python
  #multimedia
  >=media-libs/libbluray-0.6 java
  #>=media-video/libav-10 avx avx2 alsa threads truetype vorbis vpx x264 xvid
  >=media-video/ffmpeg-2.7 aac alsa fontconfig opengl truetype vorbis
  >=media-video/mpv-0.7.3 bluray dvd jpeg lua -xscreensaver -xv
  #google-chrome
  >=app-text/ghostscript-gpl-9.14 cups

  #dhcpcd: disable ipv6
  #>=net-misc/dhcpcd-6.4.3 -ipv6
  #tesseract
  >=app-text/tesseract-3 png tiff linguas_zh_TW osd
  >=media-libs/leptonica-1.71-r1 png tiff
  #imagemagick
  >=media-gfx/imagemagick-6.8 jpeg png tiff fontconfig truetype
  #java
  #>=dev-java/icedtea-bin-7 -cups
  #graphviz
  >=media-libs/gd-2.2.2 fontconfig truetype png jpeg
  # required by dev-scheme/guile-2.0.12::gentoo
  # required by sys-devel/autogen-5.18.4::gentoo
  # required by net-libs/gnutls-3.4.14::gentoo[tools]
  # required by net-print/cups-2.1.4::gentoo[ssl]
  # required by www-client/google-chrome-52.0.2743.116::gentoo
  # required by @selected
  # required by @world (argument)
  >=dev-libs/boehm-gc-7.4.2 threads

  # required by x11-base/xorg-drivers-1.19::gentoo[video_cards_i965]
  >=x11-base/xorg-server-1.19.1 glamor

  # To run fstrim periodically
  sys-process/cronie anacro

  ## Defined in Gentoo's desktop profile, missing in no-multilib.
  # required by x11-misc/xdg-utils-1.1.1-r1:0/0::gentoo
  app-text/xmlto text

  # Ilya Tumaykin <itumaykin+gentoo@gmail.com> (02 Feb 2017)
  # Enable luajit for OSC and youtube-dl support by default.
  # Override default +sdl from desktop profile and disable sdl outputs.
  # These outputs are for systems without a proper audio/video support.
  media-video/mpv lua luajit -sdl
#+END_EXAMPLE

** Overlay

*** External Overlay
Use visual-studio-code as example:
#+BEGIN_EXAMPLE
  FILE: /etc/portage/repos.conf/jorgicio.conf

  [jorgicio]
  priority = 10
  location = /usr/local/overlay/jorgicio
  sync-type = git
  sync-uri = git://github.com/jorgicio/jorgicio-gentoo.git
  auto-sync = no
#+END_EXAMPLE
Bypass all packages except ~visual-studio-code~ in this overlay:
#+BEGIN_EXAMPLE
  /etc/portage/package.mask:

  ,*/*::jorgicio

  /etc/portage/package.unmask/visual-studio-code:

  app-editors/visual-studio-code::jorgicio
#+END_EXAMPLE
Before you sync the external overlay for the first time, Portage will report this warning:
#+BEGIN_EXAMPLE
  !!! Repository 'jorgicio' is missing masters attribute in '/usr/local/overlay/jorgicio/metadata/layout.conf'
  !!! Set 'masters = gentoo' in this file for future compatibility
  WARNING: One or more repositories have missing repo_name entries:

	  /usr/local/overlay/jorgicio/profiles/repo_name

  NOTE: Each repo_name entry should be a plain text file containing a
  unique name for the repository on the first line.
#+END_EXAMPLE
It should be dispeared after you sync it:
#+BEGIN_EXAMPLE
  emaint sync -r jorgicio↲

  emerge --ask visual-studio-code↲
#+END_EXAMPLE

* Keep your Gentoo up to date

** Rolling Update in Gentoo

According to [[http://www.gentoo.org/doc/en/handbook/handbook-amd64.xml?part=2&chap=1][A Portage Introduction]]:
#+BEGIN_EXAMPLE
  # Updates  repositories
  emerge --sync↲

  # Updates system
  emerge --update --ask --deep --with-bdeps=y @world↲
  # If any of your USE flags has been altered, add "--newuse or -N" as well.
  # In abbreviation:
  emerge -uaDN --with-bdeps=y @world↲

  # Cleans the system by removing packages that are not associated
  # with explicitly merged packages.
  emerge --depclean --ask↲
  # In abbreviation:
  # emerge -ca↲
#+END_EXAMPLE

** Upgrading Kernel

Whenever ~sys-kernel/gentoo-sources~ has been updated, new kernel source will be installed at ~/usr/src/linux-X.Y.Z-gentoo~
#+BEGIN_EXAMPLE
  cd /usr/src/linux-X.Y.Z-gentoo↲
  cp ../linux/.config ./↲

  make oldconfig↲
  ## make menuconfig↲  # If necessary.

  make -j5 && make -j5 modules_install↲

  mount /dev/sdb2 /boot↲
  cp arch/x86/boot/bzImage /boot/EFI/Gentoo/gentoox64.efi↲
  umount /boot↲

  reboot↲

  # Verify the new kernel is working fine!

  # Use eselect to switch kernel!
  eselect kernel list↲
  # New kernel sits at number 2:
  eselect kernel set 2↲

  # Clean up the old kernel
  emerge --depclean --ask↲
  rm -r /usr/src/linux-(Old Kernel)-gentoo↲
  rm -r /lib/modules/(Old Kernel)-gentoo↲
#+END_EXAMPLE
NOTE: See [[https://wiki.gentoo.org/wiki/Kernel/Configuration][Gentoo::Wiki::Kernel/Configuration]], [[http://wiki.gentoo.org/wiki/Kernel/Removal][Gentoo::Wiki::Kernel/Removal]], [[file:gentoo_installation.org::#CompilingKernel][Compiling Kernel]] for further details.

* Installing software

** System Software

*** gentoolkit
#+BEGIN_EXAMPLE
  # For portage tools： equery, eclean, etc
  emerge --ask gentoolkit↲
#+END_EXAMPLE

*** NTFS
#+BEGIN_EXAMPLE
  # NTFS support
  emerge --ask ntfs3g↲
#+END_EXAMPLE

*** cronie & anacron
    :PROPERTIES:
    :CUSTOM_ID: Cronie
    :END:
See [[https://wiki.gentoo.org/wiki/Cron][Gentoo::Wiki::Cron]] for reference.
~sys-process/cronie~ has built-in ~anacron~ support which is disabled
by default. *ENABLE* it to run ~fstrim~ periodically.
#+BEGIN_EXAMPLE
  # package.use
  sys-process/cronie anacron

  emerge -aN sys-process/cronie↲

  # Make sure the cron daemon of choice has been added to the system's
  # init process. This is NOT added by default with Cronie package.
  rc-update add cronie default↲

  # Create /etc/cron.daily/fstrim：
  ---------------------------------------------------------------------
  #!/bin/sh

  /sbin/fstrim /
  EXITVALUE=$?
  if [ $EXITVALUE != 0 ]; then
      /usr/bin/logger -t logrotate "ALERT fstrim exited abnormally with [$EXITVALUE]"
  fi
  exit 0
  ---------------------------------------------------------------------
  # Ensure the fstrim script has the right permission(755).
#+END_EXAMPLE
[2017-03-21 Tue 22:11] ~/~ takes 24% disk space. For 0-30% capacity
usage, maybe a weekly fstrim is reasonable[fn:2].

*** X Window System
**** TODO Video[fn:3]
***** Kernel
#+BEGIN_EXAMPLE
  # kernel .config:
  Device Drivers  --->
       Graphics support  --->
           <*> /dev/agpgart (AGP Support)  --->
               --- /dev/agpgart (AGP Support)
               < >   AMD Opteron/Athlon64 on-CPU GART support
               -*-   Intel 440LX/BX/GX, I8xx and E7x05 chipset support
               < >   SiS chipset support
               < >   VIA chipset support
	   ...
	   <*> Direct Rendering Manager (XFree86 4.1.0 and higher DRI support)  --->
               --- Direct Rendering Manager (XFree86 4.1.0 and higher DRI support)
               [*]   Enable legacy fbdev support for your modesetting driver
	   ...
	   <*> Intel 8xx/9xx/G3x/G4x/HD Graphics
#+END_EXAMPLE
***** Drivers
Haswell 4670K's HD4600 belongs to ~i965~.
#+BEGIN_EXAMPLE
  # make.conf:
  VIDEO_CARDS="intel i965"

  emerge --ask --changed-use --deep @world↲
#+END_EXAMPLE
Here ~VIDEO_CARDS~ is a ~USE_EXPAND~ flag, which is documented in the
~profiles/desc/~ directory with one file per flag[fn:4].

The ~intel~ value is for ~x11-base/xorg-drivers~, which is the meta
package containing deps on all xorg drivers.  The ~i965~ value are for
~media-libs/mesa~.

Prior to ~xorg-drivers 1.19~, ~VIDEO_CARDS="intel i965"~ is the same
as ~VIDEO_CARDS="intel"~. ~i965~ is added in [[https://github.com/gentoo/gentoo/commit/0f26449868d8412b9629ee3b7cd4ba18427b5b36][COMMIT 0f26449]] and came
into effect from [[https://github.com/gentoo/gentoo/commit/88e99c24dc6887dce2fda053209b17d0c004aedf][COMMIT 88e99c2]].
#+BEGIN_EXAMPLE
  # xorg-drivers-1.18-r1.ebuild
  PDEPEND="
	  ...
	  video_cards_intel?         ( x11-drivers/xf86-video-intel )
	  ...
  "

  # xorg-drivers-1.19.ebuild
  PDEPEND="
	  ...
	  video_cards_i915?          ( x11-drivers/xf86-video-intel )
	  video_cards_i965?          ( >=x11-base/xorg-server-${PV}[glamor] )
	  video_cards_intel?         ( !video_cards_i965? ( x11-drivers/xf86-video-intel ) )
	  ...
  "
#+END_EXAMPLE
See [[https://devmanual.gentoo.org/eclass-reference/ebuild/index.html][Ebuild Reference]] for details about ebuild file.

***** Intel DDX & Modesetting DDX
#+BEGIN_EXAMPLE
  Beginning with x11-base/xorg-drivers-1.19, the x11-base/xorg-drivers package (in addition to the mesa package) includes support the i965 USE flag. This will omit selection of the deprecating x11-drivers/xf86-video-intel driver in favor of the more maintained, generic modesetting DDX driver built-in to x11-base/xorg-server.
#+END_EXAMPLE
For staying with Intel DDX:
#+BEGIN_EXAMPLE
  # make.conf:
  VIDEO_CARDS="intel"

  emerge -aDN @world↲
#+END_EXAMPLE
For switching over to Modesetting DDX:
#+BEGIN_EXAMPLE
  # make.conf:
  VIDEO_CARDS="intel i965"

  # package.use, add:

  # required by x11-base/xorg-drivers-1.19::gentoo[video_cards_i965]
  >=x11-base/xorg-server-1.19.1 glamor

  emerge --ask --change-use --deep @world↲
#+END_EXAMPLE
The intel DDX driver ~xf86-video-intel~ can be safely unmerged.

As of [2017-04-19 Wed 09:40], for safe transaction purpose, I keep
both of the DDX drivers. The config is the same as with modesetting
DDX, except that ~xf86-video-intel~ remains installed. We can select
one of them as shown below.

To force Xorg server to use the Intel DDX driver with SNA for hardware
accelleration:
#+BEGIN_EXAMPLE
  FILE: /etc/X11/xorg.conf.d/20-intel.conf

  # Force Intel DDX
  Section "Device"
      Identifier  "Intel Graphics"
      Driver      "intel"
      Option      "AccelMethod"    "sna"
  EndSection
#+END_EXAMPLE

To force the modesetting driver:
#+BEGIN_EXAMPLE
  FILE: /etc/portage/make.conf

  #Enable glamor globally
  USE="glamor"
  VIDEO_CARDS="intel i965"

  emerge --ask --change-use --deep @world↲

  FILE: /etc/X11/xorg.conf.d/20-modesetting.conf

  #Force modesetting DDX
  Section "Device"
      Identifier  "Intel Graphics"
      Driver      "modesetting"
      Option      "AccelMethod"    "glamor"
      Option      "DRI"            "3"
  EndSection
#+END_EXAMPLE
NOTE: Since ~dri3~ is enabled by default[fn:5]. The ~Option "DRI" "3"~
line might NOT be necessary? You can verify if ~dri3~ is enabled or
not via the following command:
#+BEGIN_EXAMPLE
  LIBGL_DEBUG=verbose mpv ...

  Output:
  ......
  libGL: pci id for fd 13: 8086:0412, driver i965
  libGL: OpenDriver: trying /usr/lib64/dri/tls/i965_dri.so
  libGL: OpenDriver: trying /usr/lib64/dri/i965_dri.so
  ......
  libGL: Using DRI3 for screen 0
  ......
#+END_EXAMPLE
***** TODO Mesa
#+BEGIN_EXAMPLE
  # package.use
  media-libs/mesa-10.2 -vaapi -llvm -gallium
#+END_EXAMPLE
***** VAAPI[fn:6]
#+BEGIN_EXAMPLE
  # Enable VAAPI globally
  ## make.conf, add:
  USE="vaapi"

  # Enabling VAAPI support will pull in the ~x11-libs/libva~ package.
  ## package.use:
  x11-libs/libva opengl

  emerge --ask --changed-use --deep @world↲
#+END_EXAMPLE
**** X Server
Additional USE flags:
#+BEGIN_EXAMPLE
  # Required in Gentoo's desktop profile

  # Jeremy Olexa <darkside@gentoo.org> (07 Oct 2011)
  # Required by mesa, ultimately by xorg-server (every desktop) bug 385843
  dev-libs/libxml2 python
#+END_EXAMPLE

#+BEGIN_EXAMPLE
  emerge --ask xorg-server↲
#+END_EXAMPLE

**** X Window Manager
#+BEGIN_EXAMPLE
  # In /etc/portage/make.conf, add:
  USE="X -gnome -kde"

  # package.use, add:
  x11-wm/fvwm png truetype vannilla

  # Install fvwm
  emerge --ask fvwm

  # Create ~/.xinitrc, add:
  exec fvwm

  # Config FVWM, run it for ONCE:
  startx↲

  # Exit X, find ~/.fvwm/.fvwm2rc:
  cd ~/.fvwm↲
  ## Recommanded in FVWM's Manual
  mv .fvwm2rc config↲
#+END_EXAMPLE
See [[https://github.com/huyuehui/config/tree/master/fvwm][My FVWM's Configuration]] for details.

**** X Terminal
#+BEGIN_EXAMPLE
  # package.use, add:
  x11-terms/rxvt-unicode 256-color xft alt-font-width -vanilla perl

  # Install
  emerge --ask rxvt-unicode↲

  # X Terminal's font
  # Create ~/.Xdefaults, add:
  URxvt.font: xft:Dejavu Sans Mono,\
	      xft:wenquanyi bitmap song
#+END_EXAMPLE

**** Language
The *OLD* way:
#+BEGIN_EXAMPLE
  # /etc/portage/make.conf
  LINGUAS="en"
#+END_EXAMPLE
The *NEW* way:

[2016-06-19 Sun], ~L10N USE_EXPAND variable replacing LINGUAS~:[fn:7]
#+BEGIN_EXAMPLE
  LINGUAS as a USE_EXPAND'ed variable is being replaced by the L10N
  variable (see below). This avoids a conceptual clash with the standard
  gettext behaviour. After a transition time for packages to be
  converted, LINGUAS will become a regular environment variable.

  eselect news list↲
   ...
   [23]     2016-06-19  L10N USE_EXPAND variable replacing LINGUAS
   ...
  eselect news read 23↲
#+END_EXAMPLE
[2017-03-20 Mon 21:26], there are still some packages, such as
~iso-codes~, that ain't L10N-compatible. Keep the ~LINGUAS~ set for
now:
#+BEGIN_EXAMPLE
  # /etc/portage/make.conf:

  L10N="en-US"

  # Will be deprecated in the future.
  LINGUAS="en"
#+END_EXAMPLE
A list of L10N values that can be used is provided as
~/usr/portage/profiles/desc/l10n.desc~. To set it per-package, edit
~/etc/portage/package.use~ and prefix the requested language packs
with ~l10n_~[fn:7].

**** TODO Font
*** Java

According to [[http://wiki.gentoo.org/wiki/Java][Gentoo::Wiki::Java]], to install ~icedtea-bin~:
#+BEGIN_EXAMPLE
  /etc/portage/package.use:
  >=dev-java/icedtea-bin-7 -cups

  emerge --ask icedtea-bin↲
#+END_EXAMPLE

For the time being[2014-10-26 Sun 06:21], ~icedtea-bin~ doesn't have built-in ~LucidaSansRegular.ttf~ font, which is required by ~libbluray~ to enable its BD-J support. Install ~LucidaSansRegular.ttf~ to ~~/.fonts~ can temporarily fix this issue. But still got some errors to play complex BD-J menus(BD-Live 2.0?). 

To install ~oracle-jdk-bin~:

#+BEGIN_EXAMPLE
  emerge --pretend oracle-jdk-bin↲

  These are the packages that would be merged, in order:

  Calculating dependencies... done!
  [ebuild  N F   ] dev-java/oracle-jdk-bin-1.8.0.45  USE="X fontconfig -alsa (-aqua) -derby -doc -examples -jce -nsplugin -pax_kernel (-selinux) -source" 

  Fetch instructions for dev-java/oracle-jdk-bin-1.8.0.45:
   ,* 
   ,* Oracle requires you to download the needed files manually after
   ,* accepting their license through a javascript capable web browser.
   ,* 
   ,* Download the following files:
   ,*   jdk-8u45-linux-x64.tar.gz
   ,* at 'http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html'
   ,* and move them to '/usr/portage/distfiles'
   ,* 
   ,* If the above mentioned urls do not point to the correct version anymore,
   ,* please download the files from Oracle's java download archive:
   ,* 
   ,*    http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u45-oth-JPR
   ,* 

  The following license changes are necessary to proceed:
   (see "package.license" in the portage(5) man page for more details)
  # required by oracle-jdk-bin (argument)
  >=dev-java/oracle-jdk-bin-1.8.0.45 Oracle-BCLA-JavaSE

  Follow the instructions, then:
  emerge --ask oracle-jdk-bin↲
#+END_EXAMPLE
*** dhcpcd
#+BEGIN_EXAMPLE
  # Upgrade from net-misc/dhcpcd-6.11.5 to net-misc/dhcpcd-7.0.0_beta3

  dhcpcd-7 has copied dhcpcd.duid and dhcpcd.secret from
  /etc to /var/lib/dhcpcd
  and copied leases in /var/lib/dhcpcd to new files with the dhcpcd-
  prefix dropped.

  You should remove these files if you don't plan on reverting
  to an older version:
	  /etc/dhcpcd.duid
	  /etc/dhcpcd.secret
	  /var/lib/dhcpcd/dhcpcd-eno1.lease
	  /var/lib/dhcpcd/dhcpcd-enp4s0.lease
	  /var/lib/dhcpcd/dhcpcd-enp4s0.lease6
#+END_EXAMPLE
** Applications

*** vim
#+BEGIN_EXAMPLE
  # Vim Editor
  emerge --ask vim↲
  ## Check
  eselect vi list↲
    [1]   vim *
    [2]   busybox
#+END_EXAMPLE

*** emacs
#+BEGIN_EXAMPLE
  # package.use
  app-editors/emacs gif jpeg png svg tiff xft

  emerge -a emacs↲
#+END_EXAMPLE
For further configurations, see [[../emacs/emacs_orgmode_setup.org][Setup Emacs]].

*** p7zip
#+BEGIN_EXAMPLE
  # Zip/Rar support
  ## package.use, add:
  app-arch/p7zip rar
  ## Install
  emerge --ask p7zip↲
#+END_EXAMPLE

*** Visual Studio Code
Install it use a third-party overlay: [[https://github.com/jorgicio/jorgicio-gentoo/tree/master/app-editors/visual-studio-code][jorgicio: visual-studio-code 1.4.0]].
See [[*External Overlay][External Overlay]].

Various programming language support: [[https://code.visualstudio.com/docs/languages/cpp][C/C++ extension]]

*** FFmpeg vs. Libav

Because ~mpv~[fn:8] prefers FFmpeg over Libav and ~Kodi(XBMC)~ requires FFmpeg, we will switch from Libav to FFmpeg.

#+BEGIN_EXAMPLE
  emerge --unmerge mpv↲
  emerge --unmerge libav↲

  # Clean their configuration
  rm /etc/portage/package.unmask/libav↲
  # Make sure 'libav' has not been unmasked
  rm -r /etc/portage/profile↲

  # Adjust USE flags
  >=media-video/ffmpeg-2.7 aac alsa fontconfig opengl truetype vorbis
  >=media-video/mpv-0.7.3 bluray dvdnav jpeg lua -xscreensaver -xv

  # FFmpeg will be pulled in by mpv automatically
  emerge --ask mpv↲

  # Clean package dependencies
  emerge --depclean↲

#+END_EXAMPLE

*** Git
#+BEGIN_EXAMPLE
  # package.use:
  dev-vcs/git -perl -python

  emerge --ask dev-vcs/git↲
#+END_EXAMPLE

*** MPV
#+BEGIN_EXAMPLE
  # package.use:

  media-video/mpv bluray dvd jpeg -xscreensaver -xv

  # Ilya Tumaykin <itumaykin+gentoo@gmail.com> (02 Feb 2017)
  # Enable luajit for OSC and youtube-dl support by default.
  # Override default +sdl from desktop profile and disable sdl outputs.
  # These outputs are for systems without a proper audio/video support.
  media-video/mpv lua luajit -sdl

  emerge --ask mpv↲
#+END_EXAMPLE
mpv also supports the VAAPI acceleration through the command-line
option ~--hwdec=vaapi~[fn:9].


* TODO Update Gigabyte BIOS

每次升级BIOS后，需要重新使用efibootmgr修改UEFI Boot Menu。详见上一篇文档。

* Footnotes

[fn:1] ~/usr/portage/profiles/targets/desktop/package.use~

[fn:2] [[http://chmatse.github.io/SSDcronTRIM/][SSDcronTRIM]]

[fn:3] [[https://wiki.gentoo.org/wiki/Intel][Gentoo::Wiki::Intel]]

[fn:4] [[https://devmanual.gentoo.org/general-concepts/use-flags/index.html][Gentoo::DEV Manual::USE Flags]]

[fn:5] 
See [[https://cgit.freedesktop.org/xorg/xserver/tree/configure.ac]["configure.ac" in Xorg source files]] for details.
See [[https://www.gnu.org/software/autoconf/manual/autoconf.html][Autoconf Manual]] for reference.
#+BEGIN_EXAMPLE
  FILE: xorg/xserver/configure.ac

  ......
  AC_ARG_ENABLE(dri2,           AS_HELP_STRING([--enable-dri2], [Build DRI2 extension (default: auto)]), [DRI2=$enableval], [DRI2=auto])
  AC_ARG_ENABLE(dri3,           AS_HELP_STRING([--enable-dri3], [Build DRI3 extension (default: auto)]), [DRI3=$enableval], [DRI3=auto])

  ......

  case x"$DRI3" in
	  xyes|xauto)
		  DRI3=yes
		  AC_DEFINE(DRI3, 1, [Build DRI3 extension])
		  DRI3_LIB='$(top_builddir)/dri3/libdri3.la'
		  SDK_REQUIRED_MODULES="$SDK_REQUIRED_MODULES $DRI3PROTO"
		  AC_MSG_NOTICE([DRI3 enabled]);
		  ;;
  esac
  ......
#+END_EXAMPLE
Modesetting DDX will use ~DRI3~ by default. But for Intel DDX, there
is a restriction:
#+BEGIN_EXAMPLE
  equery uses xf86-video-intel↲

  + + dri   : Enable direct rendering: used for accelerated 3D and some 2D, like DMA
  - - dri3  : (Restricted to <=x11-drivers/xf86-video-intel-2.99.917_p20160621)
              Enable DRI3 support
#+END_EXAMPLE
See [[https://cgit.freedesktop.org/xorg/driver/xf86-video-intel/commit/?id=9154dff9aedad3271f629edb1ccc9c8d273ca7bc][DRI3 is not supported by mesa/i915]] for details.
#+BEGIN_EXAMPLE
  # For modesetting DDX:
  man xorg.conf↲

  ......
  Option "DRI2" "boolean"
	 enable or disable DRI2. DRI2 is disabled by default.
  ......

  # For intel DDX:
  man intel↲

  ......
  Option "DRI" "string"
	 Disable  or enable DRI support. A driver name to use can be pro‐
	 vided instead of simple boolean value, which will be  passed  to
	 the  GL  implementation  for it to load the appropriate backend.
	 Alternatively the maximum level of DRI to enable (e.g. "1",  "2"
	 or "3") can be specified.

	 Default:  All levels of DRI are enabled for configurations where
	 it is supported.
  ......
#+END_EXAMPLE

[fn:6] [[https://wiki.gentoo.org/wiki/VAAPI][Gentoo::Wiki::VAAPI]]

[fn:7] [[https://wiki.gentoo.org/wiki/Localization/Guide#L10N][Gentoo::Wiki::Localization/Guide]]

[fn:8] [[https://github.com/mpv-player/mpv#ffmpeg-vs-libav][FFmpeg vs. Libav]]

[fn:9] [[https://wiki.gentoo.org/wiki/VAAPI#mpv][Gentoo::Wiki::VAAPI::mpv]]

