#+TITLE: Gentoo Linux Setup Guide
#+DATE: [2014-07-07 Mon 16:32]
#+KEYWORDS: gentoo
#+OPTIONS: H:5
#+SETUPFILE: ../org-templates/level-1.org

* User Administration

** Adding a User for Daily Use

The following table lists a number of important groups you might wish to use:
#+ATTR_HTML: :frame border
| Group | Description                                                                |
|-------+----------------------------------------------------------------------------|
| /     | <>                                                                         |
|-------+----------------------------------------------------------------------------|
| audio | be able to access the audio devices                                        |
|-------+----------------------------------------------------------------------------|
| usb   | be able to access USB devices                                              |
|-------+----------------------------------------------------------------------------|
| video | be able to access video capturing hardware and doing hardware acceleration |
|-------+----------------------------------------------------------------------------|
| users | group for normal users                                                     |
|-------+----------------------------------------------------------------------------|
| wheel | be able to use su                                                          |

#+BEGIN_EXAMPLE
  # Login as root first
  Login: root↲
  Password: (Your root password)↲

  # -m, --create-home; -G, --groups; -s, --shell
  useradd -m -G audio,usb,video,users,wheel -s /bin/bash (Your user name)↲

  passwd (Your user name)↲
  Password: (Enter the password)↲
  Re-enter password: (Re-enter the password to verify)↲
#+END_EXAMPLE

* Using Portage

** Specify Package Versions

According to [[http://wiki.gentoo.org/wiki/Version_specifier][Version Specifier]], we have:
1. Basic
   + category/package :: Matches any version of a package.
2. By Version
   + ~category/package-1.23 :: Matches version and any revision.
   + =category/package-1.23* :: Matches a version by the version range. Note that there's no "." before the "*".
   + =category/package-1.23 :: Matches a version exactly.
   + >=category/package-1.23 :: Matches the specified version or any higher version.
   + >category/package-1.23 :: Matches a version strictly later than specified.
   + <category/package-1.23 :: Matches a version strictly older than specified.
   + <=category/package-1.23 :: Matches the specified version or any older version.
3. By Slot
   + category/package:2 :: Matches package in the specified package SLOT. Note that there is no prefix.
4. By Overlay
   + category/package::overlay :: Matches a package from a specific overlay. This can be combined with other specifiers. The official portage tree is ::gentoo.

** Local Portage Configure Files

*** package.use/*

As for now, [2014-07-10 Thu 16:35], libav-10.2 & mpv-0.4.0 have been hard masked. Unmask them as following:
#+BEGIN_EXAMPLE
  cd /etc/portage/package.unmask↲

  cat libav↲

  >=media-video/libav-10

  cat mpv

  >=media-video/mpv-0.4
#+END_EXAMPLE

*** package.license

google-chrome requires explicit license acknowledgement:
#+BEGIN_EXAMPLE
  cat /etc/portage/package.license↲

  >=www-client/google-chrome-35.0.1916.114_p1 google-chrome
#+END_EXAMPLE

*** package.use

Custom USE flags for individual package. For USE flags defined in
Gentoo's profile ~desktop~[fn:2] but *missing* in ~no-multilib~, don't
forget to add them manually.
#+BEGIN_EXAMPLE
  cat /etc/portage/package.use↲

  >=dev-libs/libxml2-2.9.1-r4 python
  >=x11-wm/fvwm-2.6.5 png truetype
  >=x11-terms/rxvt-unicode-9.20 256-color xft alt-font-width -vanilla perl
  >=sys-libs/zlib-1.2.8-r1 minizip
  >=media-libs/harfbuzz-0.9.23 icu
  >=dev-libs/libxml2-2.9.1-r4 icu
  >=app-arch/p7zip-9.20.1 rar
  >=app-editors/emacs-24.3 gif jpeg png svg tiff xft
  #video
  >=x11-libs/libva-1.3.1 opengl
  >=media-libs/mesa-10.2 dri3 -vaapi -llvm -gallium

  >=dev-vcs/git-2.0 -perl -python
  #multimedia
  >=media-libs/libbluray-0.6 java
  #>=media-video/libav-10 avx avx2 alsa threads truetype vorbis vpx x264 xvid
  >=media-video/ffmpeg-2.7 aac alsa fontconfig opengl truetype vorbis
  >=media-video/mpv-0.7.3 bluray dvd jpeg lua -xscreensaver -xv
  #google-chrome
  >=app-text/ghostscript-gpl-9.14 cups

  #dhcpcd: disable ipv6
  #>=net-misc/dhcpcd-6.4.3 -ipv6
  #tesseract
  >=app-text/tesseract-3 png tiff linguas_zh_TW osd
  >=media-libs/leptonica-1.71-r1 png tiff
  #imagemagick
  >=media-gfx/imagemagick-6.8 jpeg png tiff fontconfig truetype
  #java
  #>=dev-java/icedtea-bin-7 -cups
  #graphviz
  >=media-libs/gd-2.2.2 fontconfig truetype png jpeg
  # required by dev-scheme/guile-2.0.12::gentoo
  # required by sys-devel/autogen-5.18.4::gentoo
  # required by net-libs/gnutls-3.4.14::gentoo[tools]
  # required by net-print/cups-2.1.4::gentoo[ssl]
  # required by www-client/google-chrome-52.0.2743.116::gentoo
  # required by @selected
  # required by @world (argument)
  >=dev-libs/boehm-gc-7.4.2 threads

  # required by x11-base/xorg-drivers-1.19::gentoo[video_cards_i965]
  >=x11-base/xorg-server-1.19.1 glamor

  # To run fstrim periodically
  sys-process/cronie anacro

  ## Defined in Gentoo's desktop profile, missing in no-multilib.
  # required by x11-misc/xdg-utils-1.1.1-r1:0/0::gentoo
  app-text/xmlto text

  # Ilya Tumaykin <itumaykin+gentoo@gmail.com> (02 Feb 2017)
  # Enable luajit for OSC and youtube-dl support by default.
  # Override default +sdl from desktop profile and disable sdl outputs.
  # These outputs are for systems without a proper audio/video support.
  media-video/mpv lua luajit -sdl
#+END_EXAMPLE

** Overlay

*** External Overlay
Use visual-studio-code as example:
#+BEGIN_EXAMPLE
  FILE: /etc/portage/repos.conf/jorgicio.conf

  [jorgicio]
  priority = 10
  location = /usr/local/overlay/jorgicio
  sync-type = git
  sync-uri = git://github.com/jorgicio/jorgicio-gentoo.git
  auto-sync = no
#+END_EXAMPLE
Bypass all packages except ~visual-studio-code~ in this overlay:
#+BEGIN_EXAMPLE
  /etc/portage/package.mask:

  ,*/*::jorgicio

  /etc/portage/package.unmask/visual-studio-code:

  app-editors/visual-studio-code::jorgicio
#+END_EXAMPLE
Before you sync the external overlay for the first time, Portage will report this warning:
#+BEGIN_EXAMPLE
  !!! Repository 'jorgicio' is missing masters attribute in '/usr/local/overlay/jorgicio/metadata/layout.conf'
  !!! Set 'masters = gentoo' in this file for future compatibility
  WARNING: One or more repositories have missing repo_name entries:

	  /usr/local/overlay/jorgicio/profiles/repo_name

  NOTE: Each repo_name entry should be a plain text file containing a
  unique name for the repository on the first line.
#+END_EXAMPLE
It should be dispeared after you sync it:
#+BEGIN_EXAMPLE
  emaint sync -r jorgicio↲

  emerge --ask visual-studio-code↲
#+END_EXAMPLE

* Keep your Gentoo up to date

** Rolling Update in Gentoo

According to [[http://www.gentoo.org/doc/en/handbook/handbook-amd64.xml?part=2&chap=1][A Portage Introduction]]:
#+BEGIN_EXAMPLE
  # Updates  repositories
  emerge --sync↲

  # Updates system
  emerge --update --ask --deep --with-bdeps=y @world↲
  # If any of your USE flags has been altered, add "--newuse or -N" as well.
  # In abbreviation:
  emerge -uaDN --with-bdeps=y @world↲

  # Cleans the system by removing packages that are not associated
  # with explicitly merged packages.
  emerge --depclean --ask↲
  # In abbreviation:
  # emerge -ca↲
#+END_EXAMPLE

** Upgrading Kernel

Whenever ~sys-kernel/gentoo-sources~ has been updated, new kernel source will be installed at ~/usr/src/linux-X.Y.Z-gentoo~
#+BEGIN_EXAMPLE
  cd /usr/src/linux-X.Y.Z-gentoo↲
  cp ../linux/.config ./↲

  make oldconfig↲
  ## make menuconfig↲  # If necessary.

  make -j5 && make -j5 modules_install↲

  mount /dev/sdb2 /boot↲
  cp arch/x86/boot/bzImage /boot/EFI/Gentoo/gentoox64.efi↲
  umount /boot↲

  reboot↲

  # Verify the new kernel is working fine!

  # Use eselect to switch kernel!
  eselect kernel list↲
  # New kernel sits at number 2:
  eselect kernel set 2↲

  # Clean up the old kernel
  emerge --depclean --ask↲
  rm -r /usr/src/linux-(Old Kernel)-gentoo↲
  rm -r /lib/modules/(Old Kernel)-gentoo↲
#+END_EXAMPLE
NOTE: See [[https://wiki.gentoo.org/wiki/Kernel/Configuration][Gentoo::Wiki::Kernel/Configuration]], [[http://wiki.gentoo.org/wiki/Kernel/Removal][Gentoo::Wiki::Kernel/Removal]], [[file:gentoo_installation.org::#CompilingKernel][Compiling Kernel]] for further details.

* Installing software

** System Software

*** gentoolkit
#+BEGIN_EXAMPLE
  # For portage tools： equery, eclean, etc
  emerge --ask gentoolkit↲
#+END_EXAMPLE

*** NTFS
#+BEGIN_EXAMPLE
  # NTFS support
  emerge --ask ntfs3g↲
#+END_EXAMPLE

*** cronie & anacron
    :PROPERTIES:
    :CUSTOM_ID: Cronie
    :END:
See [[https://wiki.gentoo.org/wiki/Cron][Gentoo::Wiki::Cron]] for reference.
~sys-process/cronie~ has built-in ~anacron~ support which is disabled
by default. *ENABLE* it to run ~fstrim~ periodically.
#+BEGIN_EXAMPLE
  # package.use
  sys-process/cronie anacron

  emerge -aN sys-process/cronie↲

  # Make sure the cron daemon of choice has been added to the system's
  # init process. This is NOT added by default with Cronie package.
  rc-update add cronie default↲

  # Create /etc/cron.daily/fstrim：
  ---------------------------------------------------------------------
  #!/bin/sh

  /sbin/fstrim /
  EXITVALUE=$?
  if [ $EXITVALUE != 0 ]; then
      /usr/bin/logger -t logrotate "ALERT fstrim exited abnormally with [$EXITVALUE]"
  fi
  exit 0
  ---------------------------------------------------------------------
  # Ensure the fstrim script has the right permission(755).
#+END_EXAMPLE
[2017-03-21 Tue 22:11] ~/~ takes 24% disk space. For 0-30% capacity
usage, maybe a weekly fstrim is reasonable[fn:4].

*** X Window System

**** X Server
Additional USE flags:
#+BEGIN_EXAMPLE
  # Required in Gentoo's desktop profile

  # Jeremy Olexa <darkside@gentoo.org> (07 Oct 2011)
  # Required by mesa, ultimately by xorg-server (every desktop) bug 385843
  dev-libs/libxml2 python
#+END_EXAMPLE

#+BEGIN_EXAMPLE
  emerge --ask xorg-server↲
#+END_EXAMPLE

**** X Window Manager
#+BEGIN_EXAMPLE
  # In /etc/portage/make.conf, add:
  USE="X -gnome -kde"

  # package.use, add:
  x11-wm/fvwm png truetype vannilla

  # Install fvwm
  emerge --ask fvwm

  # Create ~/.xinitrc, add:
  exec fvwm

  # Config FVWM, run it for ONCE:
  startx↲

  # Exit X, find ~/.fvwm/.fvwm2rc:
  cd ~/.fvwm↲
  ## Recommanded in FVWM's Manual
  mv .fvwm2rc config↲
#+END_EXAMPLE
See [[https://github.com/huyuehui/config/tree/master/fvwm][My FVWM's Configuration]] for details.

**** X Terminal
#+BEGIN_EXAMPLE
  # package.use, add:
  x11-terms/rxvt-unicode 256-color xft alt-font-width -vanilla perl

  # Install
  emerge --ask rxvt-unicode↲

  # X Terminal's font
  # Create ~/.Xdefaults, add:
  URxvt.font: xft:Dejavu Sans Mono,\
	      xft:wenquanyi bitmap song
#+END_EXAMPLE

**** Language
The *OLD* way:
#+BEGIN_EXAMPLE
  # /etc/portage/make.conf
  LINGUAS="en"
#+END_EXAMPLE
The *NEW* way:

[2016-06-19 Sun], ~L10N USE_EXPAND variable replacing LINGUAS~:[fn:3]
#+BEGIN_EXAMPLE
  LINGUAS as a USE_EXPAND'ed variable is being replaced by the L10N
  variable (see below). This avoids a conceptual clash with the standard
  gettext behaviour. After a transition time for packages to be
  converted, LINGUAS will become a regular environment variable.

  eselect news list↲
   ...
   [23]     2016-06-19  L10N USE_EXPAND variable replacing LINGUAS
   ...
  eselect news read 23↲
#+END_EXAMPLE
[2017-03-20 Mon 21:26], there are still some packages, such as
~iso-codes~, that ain't L10N-compatible. Keep the ~LINGUAS~ set for
now:
#+BEGIN_EXAMPLE
  # /etc/portage/make.conf:

  L10N="en-US"

  # Will be deprecated in the future.
  LINGUAS="en"
#+END_EXAMPLE
A list of L10N values that can be used is provided as
~/usr/portage/profiles/desc/l10n.desc~. To set it per-package, edit
~/etc/portage/package.use~ and prefix the requested language packs
with ~l10n_~[fn:3].

*** Java

According to [[http://wiki.gentoo.org/wiki/Java][Gentoo::Wiki::Java]], to install ~icedtea-bin~:
#+BEGIN_EXAMPLE
  /etc/portage/package.use:
  >=dev-java/icedtea-bin-7 -cups

  emerge --ask icedtea-bin↲
#+END_EXAMPLE

For the time being[2014-10-26 Sun 06:21], ~icedtea-bin~ doesn't have built-in ~LucidaSansRegular.ttf~ font, which is required by ~libbluray~ to enable its BD-J support. Install ~LucidaSansRegular.ttf~ to ~~/.fonts~ can temporarily fix this issue. But still got some errors to play complex BD-J menus(BD-Live 2.0?). 

To install ~oracle-jdk-bin~:

#+BEGIN_EXAMPLE
  emerge --pretend oracle-jdk-bin↲

  These are the packages that would be merged, in order:

  Calculating dependencies... done!
  [ebuild  N F   ] dev-java/oracle-jdk-bin-1.8.0.45  USE="X fontconfig -alsa (-aqua) -derby -doc -examples -jce -nsplugin -pax_kernel (-selinux) -source" 

  Fetch instructions for dev-java/oracle-jdk-bin-1.8.0.45:
   ,* 
   ,* Oracle requires you to download the needed files manually after
   ,* accepting their license through a javascript capable web browser.
   ,* 
   ,* Download the following files:
   ,*   jdk-8u45-linux-x64.tar.gz
   ,* at 'http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html'
   ,* and move them to '/usr/portage/distfiles'
   ,* 
   ,* If the above mentioned urls do not point to the correct version anymore,
   ,* please download the files from Oracle's java download archive:
   ,* 
   ,*    http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u45-oth-JPR
   ,* 

  The following license changes are necessary to proceed:
   (see "package.license" in the portage(5) man page for more details)
  # required by oracle-jdk-bin (argument)
  >=dev-java/oracle-jdk-bin-1.8.0.45 Oracle-BCLA-JavaSE

  Follow the instructions, then:
  emerge --ask oracle-jdk-bin↲
#+END_EXAMPLE

** Applications

*** Visual Studio Code
Install it use a third-party overlay: [[https://github.com/jorgicio/jorgicio-gentoo/tree/master/app-editors/visual-studio-code][jorgicio: visual-studio-code 1.4.0]].
See [[*External Overlay][External Overlay]].

Various programming language support: [[https://code.visualstudio.com/docs/languages/cpp][C/C++ extension]]

*** FFmpeg vs. Libav

Because ~mpv~[fn:1] prefers FFmpeg over Libav and ~Kodi(XBMC)~ requires FFmpeg, we will switch from Libav to FFmpeg.

#+BEGIN_EXAMPLE
  emerge --unmerge mpv↲
  emerge --unmerge libav↲

  # Clean their configuration
  rm /etc/portage/package.unmask/libav↲
  # Make sure 'libav' has not been unmasked
  rm -r /etc/portage/profile↲

  # Adjust USE flags
  >=media-video/ffmpeg-2.7 aac alsa fontconfig opengl truetype vorbis
  >=media-video/mpv-0.7.3 bluray dvdnav jpeg lua -xscreensaver -xv

  # FFmpeg will be pulled in by mpv automatically
  emerge --ask mpv↲

  # Clean package dependencies
  emerge --depclean↲

#+END_EXAMPLE

*** vim
#+BEGIN_EXAMPLE
  # Vim Editor
  emerge --ask vim↲
  ## Check
  eselect vi list↲
    [1]   vim *
    [2]   busybox
#+END_EXAMPLE

*** p7zip
#+BEGIN_EXAMPLE
  # Zip/Rar support
  ## package.use, add:
  app-arch/p7zip rar
  ## Install
  emerge --ask p7zip
#+END_EXAMPLE

* TODO Update Gigabyte BIOS

每次升级BIOS后，需要重新使用efibootmgr修改UEFI Boot Menu。详见上一篇文档。

* Footnotes

[fn:4] [[http://chmatse.github.io/SSDcronTRIM/][SSDcronTRIM]]

[fn:3] [[https://wiki.gentoo.org/wiki/Localization/Guide#L10N][Gentoo::Wiki::Localization/Guide]]

[fn:2] ~/usr/portage/profiles/targets/desktop/package.use~

[fn:1] [[https://github.com/mpv-player/mpv#ffmpeg-vs-libav][FFmpeg vs. Libav]]

