#+TITLE: Gentoo Linux Setup Guide
#+DATE: [2014-07-07 Mon 16:32]
#+KEYWORDS: gentoo
#+SETUPFILE: ../org-templates/level-1.org

* User Administration

** Adding a User for Daily Use

The following table lists a number of important groups you might wish to use:
#+ATTR_HTML: :frame border
| Group | Description                                                                |
|-------+----------------------------------------------------------------------------|
| /     | <>                                                                         |
|-------+----------------------------------------------------------------------------|
| audio | be able to access the audio devices                                        |
|-------+----------------------------------------------------------------------------|
| usb   | be able to access USB devices                                              |
|-------+----------------------------------------------------------------------------|
| video | be able to access video capturing hardware and doing hardware acceleration |
|-------+----------------------------------------------------------------------------|
| users | group for normal users                                                     |
|-------+----------------------------------------------------------------------------|
| wheel | be able to use su                                                          |

#+BEGIN_EXAMPLE
  # Login as root first
  Login: root↲
  Password: (Your root password)↲

  # -m, --create-home; -G, --groups; -s, --shell
  useradd -m -G audio,usb,video,users,wheel -s /bin/bash (Your user name)↲

  passwd (Your user name)↲
  Password: (Enter the password)↲
  Re-enter password: (Re-enter the password to verify)↲
#+END_EXAMPLE

* Using Portage

** Specify Package Versions

According to [[http://wiki.gentoo.org/wiki/Version_specifier][Version Specifier]], we have:
1. Basic
   + category/package :: Matches any version of a package.
2. By Version
   + ~category/package-1.23 :: Matches version and any revision.
   + =category/package-1.23* :: Matches a version by the version range. Note that there's no "." before the "*".
   + =category/package-1.23 :: Matches a version exactly.
   + >=category/package-1.23 :: Matches the specified version or any higher version.
   + >category/package-1.23 :: Matches a version strictly later than specified.
   + <category/package-1.23 :: Matches a version strictly older than specified.
   + <=category/package-1.23 :: Matches the specified version or any older version.
3. By Slot
   + category/package:2 :: Matches package in the specified package SLOT. Note that there is no prefix.
4. By Overlay
   + category/package::overlay :: Matches a package from a specific overlay. This can be combined with other specifiers. The official portage tree is ::gentoo.

** Local Portage Configure Files

*** package.use/*

As for now, [2014-07-10 Thu 16:35], libav-10.2 & mpv-0.4.0 have been hard masked. Unmask them as following:
#+BEGIN_EXAMPLE
  cd /etc/portage/package.unmask↲

  cat libav↲

  >=media-video/libav-10

  cat mpv

  >=media-video/mpv-0.4
#+END_EXAMPLE

*** package.license

google-chrome requires explicit license acknowledgement:
#+BEGIN_EXAMPLE
  cat /etc/portage/package.license↲

  >=www-client/google-chrome-35.0.1916.114_p1 google-chrome
#+END_EXAMPLE

*** package.use

Custom USE flags for individual package:
#+BEGIN_EXAMPLE
  cat /etc/portage/package.use↲

  >=dev-libs/libxml2-2.9.1-r4 python
  >=x11-wm/fvwm-2.6.5 png truetype
  >=x11-terms/rxvt-unicode-9.20 256-color xft alt-font-width -vanilla perl
  >=sys-libs/zlib-1.2.8-r1 minizip
  >=media-libs/harfbuzz-0.9.23 icu
  >=dev-libs/libxml2-2.9.1-r4 icu
  >=app-arch/p7zip-9.20.1 rar
  ~app-editors/emacs-24.3 gif jpeg png svg tiff xft
  >=x11-libs/libva-1.3.1 opengl
  >=media-libs/mesa-10.2 dri3
  >=dev-vcs/git-2.0 -perl -python
  #>=media-video/libav-9 avx threads truetype vorbis vpx x264 xvid
  >=media-video/libav-10 avx avx2 alsa threads truetype vorbis vpx x264 xvid
  >=media-video/mpv-0.3.10 bluray dvdnav jpeg lua -xscreensaver -xv
  #google-chrome
  >=app-text/ghostscript-gpl-9.14 cups
  #goagent
  >=dev-libs/nss-3.16 utils
  #golang
  >=dev-lang/go-1.2.2 emacs
#+END_EXAMPLE

* Keep your Gentoo up to date

** Rolling Update in Gentoo

According to [[http://www.gentoo.org/doc/en/handbook/handbook-amd64.xml?part=2&chap=1][A Portage Introduction]]:
#+BEGIN_EXAMPLE
  # Updates  repositories
  emerge --sync↲

  # Updates system
  emerge --update --ask --deep --with-bdeps=y @world↲
  # If any of your USE flags has been altered, add "--newuse or -N" as well.
  # In abbreviation:
  emerge -uaDN --with-bdeps=y @world↲

  # Cleans the system by removing packages that are not associated
  # with explicitly merged packages.
  emerge --depclean --ask↲
  # In abbreviation:
  # emerge -ca↲
#+END_EXAMPLE

** Upgrading Kernel

Whenever ~sys-kernel/gentoo-sources~ has been updated, new kernel source will be installed at ~/usr/src/linux-X.Y.Z-gentoo~
#+BEGIN_EXAMPLE
  cd /usr/src/linux-X.Y.Z-gentoo↲
  cp ../linux/.config ./↲

  make oldconfig↲
  ## make menuconfig↲  # If necessary.

  make -j5 && make -j5 modules_install↲

  mount /dev/sdb2 /boot↲
  cp arch/x86/boot/bzImage /boot/EFI/Gentoo/gentoox64.efi↲
  umount /boot↲

  reboot↲

  # Verify the new kernel is working fine!

  # Use eselect to switch kernel!
  eselect kernel list↲
  # New kernel sits at number 2:
  eselect kernel set 2↲

  # Clean up the old kernel
  emerge --depclean --ask↲
  rm -r /usr/src/linux-(Old Kernel)-gentoo↲
  rm -r /lib/modules/(Old Kernel)-gentoo↲
#+END_EXAMPLE
NOTE: See [[https://wiki.gentoo.org/wiki/Kernel/Configuration][Gentoo::Wiki::Kernel/Configuration]], [[http://wiki.gentoo.org/wiki/Kernel/Removal][Gentoo::Wiki::Kernel/Removal]], [[file:gentoo_installation.org::#CompilingKernel][Compiling Kernel]] for further details.

* Installing software

** Necessary System Tools

*** Java

According to [[http://wiki.gentoo.org/wiki/Java][Gentoo::Wiki::Java]], to install ~icedtea-bin~:
#+BEGIN_EXAMPLE
  /etc/portage/package.use:
  >=dev-java/icedtea-bin-7 -cups

  emerge --ask icedtea-bin↲
#+END_EXAMPLE

For the time being[2014-10-26 Sun 06:21], ~icedtea-bin~ doesn't have built-in ~LucidaSansRegular.ttf~ font, which is required by ~libbluray~ to enable its BD-J support. Install ~LucidaSansRegular.ttf~ to ~~/.fonts~ can temporarily fix this issue. But still got some errors to play complex BD-J menus(BD-Live 2.0?). 

To install ~oracle-jdk-bin~:

#+BEGIN_EXAMPLE
  emerge --pretend oracle-jdk-bin↲

  Calculating dependencies... done!
  [ebuild  N F   ] dev-java/oracle-jdk-bin-1.8.0.25  USE="X fontconfig -alsa (-aqua) -derby -doc -examples -jce -nsplugin -pax_kernel (-selinux) -source" 

  Fetch instructions for dev-java/oracle-jdk-bin-1.8.0.25:
   ,* 
   ,* Oracle requires you to download the needed files manually after
   ,* accepting their license through a javascript capable web browser.
   ,* 
   ,* Download the following files:
   ,*   jdk-8u25-linux-x64.tar.gz
   ,* at 'http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html'
   ,* and move them to '/usr/portage/distfiles'
   ,* 

  The following license changes are necessary to proceed:
   (see "package.license" in the portage(5) man page for more details)
  # required by oracle-jdk-bin (argument)
  >=dev-java/oracle-jdk-bin-1.8.0.25 Oracle-BCLA-JavaSE


  Follow the instructions, then:
  emerge --ask oracle-jdk-bin↲
#+END_EXAMPLE

** Applications

* TODO Update Gigabyte BIOS

每次升级BIOS后，需要重新使用efibootmgr修改UEFI Boot Menu。详见上一篇文档。
